# General
title: iune
description: Libre graphic designer
author:
    name: Iune Trecet Obeso
    email: contact@iune.info
    github: iunetrecet
    flickr: https://flickr.com/photos/iunetrecet/
timezone: "Europe/Paris"

# Collections
collections:
    projects:
        output: true


# URLs
production_url: http://iune.info/
permalink: /:categories/:year/:month/:day/:title

# Jekyll
exclude: [".rvmrc", ".rbenv-version", "Rakefile", "vendor"]
excerpt_separator: "\n"
highlighter: true
markdown: redcarpet
sass:
    sass_dir: _sass
    style: :compressed
redcarpet:
    extensions: ["tables", "autolink", "fenced_code_blocks", "superscript",
                "quote", "footnotes"]

JB:
    BASE_PATH: false
    ASSET_PATH: /static/
    atom_path: /atom.xml
    rss_path: /rss.xml
    comments:
        provider: false
    analytics:
        provider: false
    sharing:
        provider: false
